using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TaskApp.Dtos;

//Data annotations wont work without importing endpoint filters 
public record class CreateTaskDto( 
    [Required] [Range(-100,100)] int UserId,//!!neg values are for seed data otherwise id auto generated by user entity is positive
    [Required]string TaskTitle, 
    [Required]string TaskDescription,
    [Required]DateTime TaskDate, 
    [DefaultValue(false)]bool Status,
    string TaskPriority, 
    DateOnly DateCreated
);

