GET http://localhost:5148

###
GET http://localhost:5148/tasks

###
GET http://localhost:5148/tasks/1

###
POST http://localhost:5148/tasks
Content-Type: application/json

{ 
  "userId": -3,
  "taskTitle": "Washing Dishes",
  "taskDescription": "The dishes must be washed ",
  "taskDate": "2025-02-20T12:58:58.2808009+05:00",
  "status": false,
  "taskPriority": "High",
  "dateCreated": "2025-02-20"
}

###
PUT http://localhost:5148/tasks/11
Content-Type: application/json

{ 
  "userId": 3,
  "taskTitle": "Task updated",
  "taskDescription": "Task description updated",
  "taskDate": "2025-02-20T12:58:58.2808009+05:00",
  "status": true,
  "taskPriority": "Low",
  "dateCreated": "2025-02-20"
}

###
DELETE http://localhost:5148/tasks/11